# Generated by Django 3.2.8 on 2022-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
