# Generated by Django 3.2.8 on 2022-06-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_user',
            name='photo',
            field=models.ImageField(blank=True, max_length=256, upload_to='user_icon/%Y%m%d/'),
        ),
    ]
