# Generated by Django 3.2.8 on 2022-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_user',
            name='photo',
            field=models.ImageField(blank=True, default='/media/user_icon/default/default.png', max_length=256, upload_to='user_icon/%Y%m%d/'),
        ),
    ]
