# Generated by Django 3.2.8 on 2022-07-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_user',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
