# Generated by Django 3.2.8 on 2022-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articlepost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='photo',
            field=models.ImageField(blank=True, max_length=256, upload_to='editor/Title/'),
        ),
    ]
