# Generated by Django 3.2.8 on 2022-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='photo',
            field=models.ImageField(blank=True, max_length=256, upload_to='blog_covers/%Y%m%d/'),
        ),
    ]
